### ISSUE TITLE
can this be used on MNIST data to cluster?

### ISSUE THREAD

**Issue by saravananoppila** [mpatacchiola/pyERA#2]
Hi @mpatacchiola 
can this algorithm be used to cluster multiple image?

**Comment by mpatacchiola** [comment]
Hi @saravananoppila yes it can be easily used to do so. An image is just a vector when it is flattened and SOMs can manage to cluster them (see [here](https://wonikjang.github.io/deeplearning_unsupervised_som/2017/06/30/som.html) for an example). However, for more appealing results I suggest to use [t-SNE](https://en.wikipedia.org/wiki/T-distributed_stochastic_neighbor_embedding) on images since it is more effective in clustering high-dimensional data (see [here](https://colah.github.io/posts/2014-10-Visualizing-MNIST/) for an example).
